pipeline:
  - name: onboardtest
    watchdog: 600
    git:
      url: https://github.com/mirmik/onboardtest
      name: onboardtest
    steps:
      - name: make
        run: ./make.py

      - name: install
        run: sudo ./make.py install

      - name: licant-libs
        run: licant-libs .

    success_info: "Pipeline: {{pipeline_name}}\nCommit: {{commit_hash}}\nMessage: {{commit_message}}\n"
